version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: archdb
      POSTGRES_DB: budgeting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: archdb
      POSTGRES_DB: budgeting
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:archdb@db/budgeting
    depends_on:
      - db
    command: >
      sh -c "python init_db.py && uvicorn service_jwt:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app

volumes:
  postgres_data: